name: Encoding, Naming, and Folder Validation

on:
  push:
    branches: [develop]
 
  pull_request:
    branches: [ develop]
    types: [opened, synchronize, reopened]

jobs:
  validate-encoding-naming-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install charset-normalizer
        run: |
          pip install charset-normalizer

      - name: Find relevant files
        id: filelist
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1 || true
          # Get changed files in the PR or push
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} > files.txt
          else
            git diff --name-only HEAD~1 > files.txt
          fi
          cat files.txt

      - name: Run encoding, naming, and folder checks
        run: |
          if [[ -s files.txt ]]; then
            python .github/check_encoding.py $(cat files.txt)
          else
            echo "No relevant files changed."
          fi
